-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.admins
(
    "adminId" integer NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("adminId")
);

CREATE TABLE public.bookings
(
    "bookingId" integer NOT NULL,
    "userEmail" character varying(255),
    "VehicleId" integer NOT NULL,
    "userId" integer NOT NULL,
    "bookingDate" character varying(255),
    "returnDate" character varying(255),
    status boolean,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("bookingId")
);

CREATE TABLE public.brands
(
    "brandId" integer NOT NULL,
    "brandName" character varying(255) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("brandId")
);

CREATE TABLE public.contact_messages
(
    "ID" integer NOT NULL,
    "userId" integer NOT NULL,
    "fullName" character varying(255),
    email character varying(255),
    address character varying(255),
    contact character varying(255),
    dob text,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("ID")
);

CREATE TABLE public.migrations
(
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.payments
(
    "paymentId" integer NOT NULL,
    "userId" integer NOT NULL,
    "fullName" character varying(255) NOT NULL,
    "bookingId" integer NOT NULL,
    "paymentAmount" integer NOT NULL,
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("paymentId")
);

CREATE TABLE public.subscribers
(
    "ID" integer NOT NULL,
    "userId" integer NOT NULL,
    "subscriberEmail" character varying(255) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("ID")
);

CREATE TABLE public.testimonials
(
    "ID" integer NOT NULL,
    "userId" integer NOT NULL,
    "userEmail" character varying(255) NOT NULL,
    testimonial text NOT NULL,
    status boolean NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("ID")
);

CREATE TABLE public.users
(
    "userId" integer NOT NULL,
    "fullName" character varying(255),
    email character varying(255),
    password character varying(255),
    contact character varying(255),
    dob character varying(255),
    address character varying(255),
    city character varying(255),
    country character varying(255),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("userId")
);

CREATE TABLE public.vehicles
(
    "VehicleId" integer NOT NULL,
    "brandId" integer,
    "VehiclesTitle" character varying(255),
    "VehiclesBrand" character varying(255),
    "VehiclesOverview" text,
    "PricePerDay" integer,
    "FuelType" character varying(255),
    "ModelYear" integer,
    "SeatingCapacity" integer,
    "Vimage1" character varying(255),
    "Vimage2" character varying(255),
    "Vimage3" character varying(255),
    "Vimage4" character varying(255),
    "Vimage5" character varying(255),
    "AirConditioner" boolean,
    "PowerDoorLocks" boolean,
    "AntiLockBrakingSystem" boolean,
    "BrakeAssist" boolean,
    "PowerSteering" boolean,
    "DriverAirbag" boolean,
    "PassengerAirbag" boolean,
    "CDPlayer" boolean,
    "CentralLocking" boolean,
    "CrashSensor" boolean,
    "LeatherSeats" boolean,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    PRIMARY KEY ("VehicleId")
);

ALTER TABLE public.bookings
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users ("userId")
    NOT VALID;


ALTER TABLE public.bookings
    ADD FOREIGN KEY ("VehicleId")
    REFERENCES public.vehicles ("VehicleId")
    NOT VALID;


ALTER TABLE public.contact_messages
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users ("userId")
    NOT VALID;


ALTER TABLE public.payments
    ADD FOREIGN KEY ("bookingId")
    REFERENCES public.bookings ("bookingId")
    NOT VALID;


ALTER TABLE public.payments
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users ("userId")
    NOT VALID;


ALTER TABLE public.subscribers
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users ("userId")
    NOT VALID;


ALTER TABLE public.testimonials
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users ("userId")
    NOT VALID;


ALTER TABLE public.vehicles
    ADD FOREIGN KEY ("brandId")
    REFERENCES public.brands ("brandId")
    NOT VALID;

END;